# Generated by Django 4.1.3 on 2022-11-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[(0, 'Analgésico'), (1, 'Anestésico'), (2, 'Antibiótico'), (3, 'Anticonceptivo'), (4, 'Ansiolítico')], max_length=50)),
                ('formula', models.BinaryField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cliente')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medicamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
